# Generated by Django 4.2.1 on 2023-05-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_val', models.CharField(max_length=20, verbose_name='Ціна')),
                ('p_description', models.CharField(max_length=200, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Ціна',
                'verbose_name_plural': 'Ціни',
            },
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=200, verbose_name='Послуга')),
                ('p_old', models.CharField(max_length=200, verbose_name='Стара ціна')),
                ('p_new', models.CharField(max_length=200, verbose_name='Нова')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
            },
        ),
    ]
