# Generated by Django 4.2.1 on 2023-05-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecard',
            options={'verbose_name': 'Ціну', 'verbose_name_plural': 'Ціни'},
        ),
        migrations.AlterModelOptions(
            name='pricetable',
            options={'verbose_name': 'Послугу', 'verbose_name_plural': 'Послуги'},
        ),
    ]
