# Generated by Django 4.2.1 on 2023-05-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_date', models.DateTimeField(auto_now=True)),
                ('o_name', models.CharField(max_length=200)),
                ('o_phone', models.CharField(max_length=200)),
            ],
        ),
    ]
