# Generated by Django 4.2.1 on 2023-05-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_statuscrm_orders_o_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentCrm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment_text', models.TextField(verbose_name='Текст коменту')),
                ('coment_db', models.DateTimeField(auto_now=True, verbose_name='Дата створення')),
                ('coment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.orders', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Коментарій',
                'verbose_name_plural': 'Коментарії',
            },
        ),
    ]
